version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: opengisch/qt-ndk:5.13.0

    working_directory: ~

    steps:
      - checkout

      # Build the image
      - run: docker build -t opengisch/qfield-sdk:2019someday .
